- name: Run Markdownlint
  # Usamos la acción oficial que es más estable
  uses: davidanson/markdownlint-cli2-action@v16
  with:
    # Busca automáticamente el archivo .markdownlint.json o .markdownlint-cli2.jsonc
    config: '.markdownlint.json'
    # Revisa todos los archivos markdown
    globs: '**/*.md'